# Generated by Django 4.2.7 on 2023-11-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe_associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_tontinier', models.BooleanField(default=False)),
                ('status_user', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('COLLECTED', 'COLLECTED'), ('NOT_COLLECTED', 'NOT_COLLECTED')], default='NOT_COLLECTED', max_length=20)),
                ('invitation_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('collection_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField()),
                ('is_pay_penality', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe_associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tontine.groupe_associate')),
            ],
        ),
        migrations.CreateModel(
            name='Groupes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INSCRIPTION', 'INSCRIPTION'), ('IN_PROGESS', 'IN_PROGESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='INSCRIPTION', max_length=20)),
                ('start_date', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.TextField(null=True)),
                ('contribution_period', models.CharField(choices=[('DAY', 'DAY'), ('WEEK', 'WEEK'), ('MONTH', 'MONTH')], max_length=10)),
                ('time_contribution', models.TimeField(default='10:00')),
                ('day_contribution', models.CharField(choices=[('MON', 'LUNDI'), ('TUE', 'MARDI'), ('WED', 'MERCREDI'), ('THU', 'JEUDI'), ('FRI', 'VENDREDI'), ('SAT', 'SAMEDI'), ('SUN', 'DIMANCHE')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tontinier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupe_associate',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tontine.groupes'),
        ),
        migrations.AddField(
            model_name='groupe_associate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('number_day', models.IntegerField()),
                ('gain', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online', models.BooleanField(default=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tontinier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Associate_carte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COLLECTED', 'COLLECTED'), ('NOT_COLLECTED', 'NOT_COLLECTED')], default='NOT_COLLECTED', max_length=20)),
                ('collection_date', models.DateTimeField(null=True)),
                ('invitation_status', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'EXPIRED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=20)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED'), ('PENDING_CONFIRMATION', 'PENDING_CONFIRMATION'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('PROCESSING', 'PROCESSING'), ('REFUNDED', 'REFUNDED'), ('UNKNOWN', 'UNKNOWN')], max_length=20, null=True)),
                ('reseau_transaction_id', models.CharField(max_length=255, null=True)),
                ('external_id', models.CharField(max_length=255, null=True, unique=True)),
                ('referenceId', models.CharField(max_length=255, null=True, unique=True)),
                ('data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tontine.cartes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
