# Generated by Django 4.2.7 on 2023-11-23 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe_associate',
            name='status_tontinier',
        ),
        migrations.RemoveField(
            model_name='groupe_associate',
            name='status_user',
        ),
    ]
