# Generated by Django 4.2.7 on 2023-11-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0002_remove_groupe_associate_status_tontinier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe_associate',
            name='date_collect',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='groupe_associate',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
