# Generated by Django 4.2.7 on 2023-11-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tontine', '0003_groupe_associate_date_collect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate_carte',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'COLLECTED'), ('REQUEST_SENT', 'REQUEST_SENT'), ('REQUEST_IN_PROGRESS', 'REQUEST_IN_PROGRESS'), ('NOT_COLLECTED', 'NOT_COLLECTED')], default='NOT_COLLECTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe_associate',
            name='status',
            field=models.CharField(choices=[('COLLECTED', 'COLLECTED'), ('REQUEST_SENT', 'REQUEST_SENT'), ('REQUEST_IN_PROGRESS', 'REQUEST_IN_PROGRESS'), ('NOT_COLLECTED', 'NOT_COLLECTED')], default='NOT_COLLECTED', max_length=20),
        ),
    ]
