# Generated by Django 4.2.7 on 2023-11-23 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('online', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('CARTES', 'CARTES'), ('GROUPES', 'GROUPES'), ('COMMUN', 'COMMUN')], max_length=255)),
                ('key', models.CharField(max_length=255, null=True, unique=True)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Datetime'), ('SELECT', 'Select'), ('CHECKBOX', 'Checkbox'), ('RADIO', 'Radio'), ('FILE', 'File'), ('IMAGE', 'Image'), ('URL', 'Url')], max_length=255)),
                ('default_value', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('CARTES', 'CARTES'), ('GROUPES', 'GROUPES')], max_length=255)),
                ('carte_or_groupe_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TontineRule.rules')),
            ],
        ),
    ]
