# Generated by Django 4.2.7 on 2023-11-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_transaction_is_send_transaction_receiver_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_send',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_data',
            field=models.JSONField(null=True),
        ),
    ]
