# Generated by Django 4.2.7 on 2023-11-23 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('interval_user_min', models.IntegerField()),
                ('interval_user_max', models.IntegerField()),
                ('interval_groupe_min', models.IntegerField()),
                ('interval_groupe_max', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TontinierAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_date', models.DateField(null=True)),
                ('status_abonnement', models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('FINISH', 'FINISH'), ('NO_VALIDATE', 'NO_VALIDATE')], default='NO_VALIDATE', max_length=50)),
                ('is_default', models.BooleanField(default=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=60)),
                ('data', models.JSONField()),
                ('transaction_state', models.CharField(choices=[('PAYE', 'PAYE'), ('NO_PAYE', 'NO_PAYE')], default='NO_PAYE', max_length=50)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED'), ('PENDING_CONFIRMATION', 'PENDING_CONFIRMATION'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('PROCESSING', 'PROCESSING'), ('REFUNDED', 'REFUNDED'), ('UNKNOWN', 'UNKNOWN')], max_length=20, null=True)),
                ('reseau_transaction_id', models.CharField(max_length=255, null=True)),
                ('external_id', models.CharField(max_length=255, null=True, unique=True)),
                ('referenceId', models.CharField(max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Abonnement.abonnement')),
                ('tontinier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
