# Generated by Django 4.2.7 on 2023-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonnement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonnement',
            name='interval_groupe_max',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='interval_groupe_min',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='interval_user_max',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='interval_user_min',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='can_create_carte',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abonnement',
            name='can_create_groupe',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
